// Generated by CoffeeScript 1.12.7
(function() {
  var assert, gqpublicip;

  gqpublicip = require('../index.js');

  assert = require('assert');

  it("should be able to get public ip", function(done) {
    return gqpublicip(null, function(e, ip) {
      console.log(ip);
      assert(ip);
      return done(e);
    });
  });

}).call(this);

//# sourceMappingURL=test.js.map
