// Generated by CoffeeScript 2.0.0
(function() {
  var assert, gqpublicip, ip1;

  gqpublicip = require('../index.js');

  assert = require('assert');

  it("should be able to get private ip", function(done) {
    return gqpublicip.getPrivateIp(null, function(e, ip) {
      console.log(ip);
      assert(ip);
      return done(e);
    });
  });

  ip1 = "";

  it("should be able to get public ip", function(done) {
    return gqpublicip.getPublicIp(null, function(e, ip) {
      console.log(ip);
      assert(ip);
      ip1 = ip;
      return done(e);
    });
  });

  it("should be able to get public ip2", function(done) {
    console.log('dropped this path');
    return done();
  });

  //  gqpublicip.getPublicIp3 null,(e,ip)->
  //    console.log ip
  //    assert ip
  //    done e
  it("should be able to get public ip3", function(done) {
    console.log('dropped this path');
    return done();
  });

  //  gqpublicip.getPublicIp3 null,(e,ip)->
  //    console.log ip
  //    assert ip
  //    done e
  it("should be able to get public ip4", function(done) {
    return gqpublicip.getPublicIp4(null, function(e, ip) {
      console.log(ip);
      assert(ip);
      assert(ip === ip1);
      return done(e);
    });
  });

  it("should be able to get public ip5", function(done) {
    return gqpublicip.getPublicIp5(null, function(e, ip) {
      console.log(ip);
      assert(ip);
      assert(ip === ip1);
      return done(e);
    });
  });

}).call(this);

//# sourceMappingURL=test.js.map
