// Generated by CoffeeScript 1.12.7
(function() {
  var myIP;

  myIP = require('my-ip');

  module.exports = function(o, cb) {
    var e, ip;
    ip = null;
    try {
      ip = myIP();
      return cb(null, ip);
    } catch (error) {
      e = error;
      return cb(e);
    }
  };

}).call(this);

//# sourceMappingURL=index.js.map
