// Generated by CoffeeScript 1.6.3
(function() {
  var https;

  https = require('https');

  this.getPublicIp = function(cb) {
    var req;
    process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
    req = https.get('https://bot.whatismyipaddress.com', function(res) {
      res.setEncoding('utf8');
      res.on('data', function(chunk) {
        return cb(null, chunk);
      });
      return res.on('error', function(e) {
        return cb(null, "unknown");
      });
    });
    req.on('error', function(e) {
      return cb(null, "unknown");
    });
    return req.setTimeout(3000, function() {
      return req.destroy();
    });
  };

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
